/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author andri
 */
public class AbrirOrdemServicoGUI extends javax.swing.JFrame {

    /**
     * Creates new form AbrirOrdemServicoGUI
     */
    public AbrirOrdemServicoGUI() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabelCabecalhoAbrirOrdemServico = new javax.swing.JLabel();
        jLabelNomeClienteAbrirOrdemServico = new javax.swing.JLabel();
        jLabelContatoClienteAbrirOrdemServico = new javax.swing.JLabel();
        jLabelEnderecoClienteAbrirOrdemServico = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelEquipamentoAbrirOrdemServico = new javax.swing.JLabel();
        jLabelDescricaoAbrirOrdemServico = new javax.swing.JLabel();
        jLabelDataAbrirOrdemServico = new javax.swing.JLabel();
        jLabelStatusAbrirOrdemServico = new javax.swing.JLabel();
        jLabelValorAbrirOrdemServico = new javax.swing.JLabel();
        txtNomeClienteAbrirOrdemServico = new javax.swing.JTextField();
        txtContatoClienteAbrirOrdemServico = new javax.swing.JTextField();
        txtEnderecoClienteAbrirOrdemServico = new javax.swing.JTextField();
        txtEquipamentoAbrirOrdemServico = new javax.swing.JTextField();
        txtDataAbrirOrdemServico = new javax.swing.JTextField();
        txtValorAbrirOrdemServico = new javax.swing.JTextField();
        jComboStatusAbrirOrdemServico = new javax.swing.JComboBox<>();
        jButtonAbrirOrdemServico = new javax.swing.JButton();
        jButtonLimparCamposAbrirOrdemServico = new javax.swing.JButton();
        txtDescricaoAbrirOrdemServico = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Abrir Ordem de Serviço");
        setMinimumSize(new java.awt.Dimension(509, 367));
        setResizable(false);

        jLabelCabecalhoAbrirOrdemServico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCabecalhoAbrirOrdemServico.setText("ABRIR ORDEM DE SERVIÇO");

        jLabelNomeClienteAbrirOrdemServico.setText("Nome do Cliente");

        jLabelContatoClienteAbrirOrdemServico.setText("Contato");

        jLabelEnderecoClienteAbrirOrdemServico.setText("Endereço");

        jLabelEquipamentoAbrirOrdemServico.setText("Equipamento");

        jLabelDescricaoAbrirOrdemServico.setText("Descrição do Serviço");

        jLabelDataAbrirOrdemServico.setText("Data");

        jLabelStatusAbrirOrdemServico.setText("Status");

        jLabelValorAbrirOrdemServico.setText("Valor");

        txtNomeClienteAbrirOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteAbrirOrdemServicoActionPerformed(evt);
            }
        });

        txtContatoClienteAbrirOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContatoClienteAbrirOrdemServicoActionPerformed(evt);
            }
        });

        txtEnderecoClienteAbrirOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoClienteAbrirOrdemServicoActionPerformed(evt);
            }
        });

        txtEquipamentoAbrirOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEquipamentoAbrirOrdemServicoActionPerformed(evt);
            }
        });

        txtDataAbrirOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataAbrirOrdemServicoActionPerformed(evt);
            }
        });

        txtValorAbrirOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorAbrirOrdemServicoActionPerformed(evt);
            }
        });

        jComboStatusAbrirOrdemServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concluída", "Em aberto" }));
        jComboStatusAbrirOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboStatusAbrirOrdemServicoActionPerformed(evt);
            }
        });

        jButtonAbrirOrdemServico.setText("Abrir Ordem de Serviço");
        jButtonAbrirOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirOrdemServicoActionPerformed(evt);
            }
        });

        jButtonLimparCamposAbrirOrdemServico.setText("Limpar Campos");
        jButtonLimparCamposAbrirOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparCamposAbrirOrdemServicoActionPerformed(evt);
            }
        });

        txtDescricaoAbrirOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoAbrirOrdemServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabelCabecalhoAbrirOrdemServico))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeClienteAbrirOrdemServico)
                            .addComponent(jLabelContatoClienteAbrirOrdemServico)
                            .addComponent(jLabelEnderecoClienteAbrirOrdemServico))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContatoClienteAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeClienteAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnderecoClienteAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDataAbrirOrdemServico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelStatusAbrirOrdemServico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboStatusAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelDescricaoAbrirOrdemServico)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDescricaoAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelEquipamentoAbrirOrdemServico)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEquipamentoAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelValorAbrirOrdemServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimparCamposAbrirOrdemServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAbrirOrdemServico)
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCabecalhoAbrirOrdemServico)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeClienteAbrirOrdemServico)
                    .addComponent(txtNomeClienteAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContatoClienteAbrirOrdemServico)
                    .addComponent(txtContatoClienteAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEnderecoClienteAbrirOrdemServico)
                    .addComponent(txtEnderecoClienteAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEquipamentoAbrirOrdemServico)
                    .addComponent(txtEquipamentoAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDescricaoAbrirOrdemServico)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDataAbrirOrdemServico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelValorAbrirOrdemServico))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDataAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelStatusAbrirOrdemServico)
                                    .addComponent(jComboStatusAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtValorAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonLimparCamposAbrirOrdemServico)
                                    .addComponent(jButtonAbrirOrdemServico)))))
                    .addComponent(txtDescricaoAbrirOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeClienteAbrirOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteAbrirOrdemServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteAbrirOrdemServicoActionPerformed

    private void txtContatoClienteAbrirOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContatoClienteAbrirOrdemServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContatoClienteAbrirOrdemServicoActionPerformed

    private void txtEnderecoClienteAbrirOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoClienteAbrirOrdemServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoClienteAbrirOrdemServicoActionPerformed

    private void txtEquipamentoAbrirOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEquipamentoAbrirOrdemServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEquipamentoAbrirOrdemServicoActionPerformed

    private void txtDescricaoAbrirOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoAbrirOrdemServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoAbrirOrdemServicoActionPerformed

    private void txtDataAbrirOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataAbrirOrdemServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataAbrirOrdemServicoActionPerformed

    private void txtValorAbrirOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorAbrirOrdemServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorAbrirOrdemServicoActionPerformed

    private void jComboStatusAbrirOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboStatusAbrirOrdemServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboStatusAbrirOrdemServicoActionPerformed

    private void jButtonLimparCamposAbrirOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparCamposAbrirOrdemServicoActionPerformed
        // TODO add your handling code here:
        txtNomeClienteAbrirOrdemServico.setText("");
        txtContatoClienteAbrirOrdemServico.setText("");
        txtEnderecoClienteAbrirOrdemServico.setText("");
        txtEquipamentoAbrirOrdemServico.setText("");
        txtDescricaoAbrirOrdemServico.setText("");
        txtDataAbrirOrdemServico.setText("");
        txtValorAbrirOrdemServico.setText("");          
    }//GEN-LAST:event_jButtonLimparCamposAbrirOrdemServicoActionPerformed

    private void jButtonAbrirOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirOrdemServicoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Ordem de Serviço aberta com sucesso!", "Abrir Ordem de Serviço", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonAbrirOrdemServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbrirOrdemServicoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbrirOrdemServicoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbrirOrdemServicoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbrirOrdemServicoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbrirOrdemServicoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirOrdemServico;
    private javax.swing.JButton jButtonLimparCamposAbrirOrdemServico;
    private javax.swing.JComboBox<String> jComboStatusAbrirOrdemServico;
    private javax.swing.JLabel jLabelCabecalhoAbrirOrdemServico;
    private javax.swing.JLabel jLabelContatoClienteAbrirOrdemServico;
    private javax.swing.JLabel jLabelDataAbrirOrdemServico;
    private javax.swing.JLabel jLabelDescricaoAbrirOrdemServico;
    private javax.swing.JLabel jLabelEnderecoClienteAbrirOrdemServico;
    private javax.swing.JLabel jLabelEquipamentoAbrirOrdemServico;
    private javax.swing.JLabel jLabelNomeClienteAbrirOrdemServico;
    private javax.swing.JLabel jLabelStatusAbrirOrdemServico;
    private javax.swing.JLabel jLabelValorAbrirOrdemServico;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtContatoClienteAbrirOrdemServico;
    private javax.swing.JTextField txtDataAbrirOrdemServico;
    private javax.swing.JTextField txtDescricaoAbrirOrdemServico;
    private javax.swing.JTextField txtEnderecoClienteAbrirOrdemServico;
    private javax.swing.JTextField txtEquipamentoAbrirOrdemServico;
    private javax.swing.JTextField txtNomeClienteAbrirOrdemServico;
    private javax.swing.JTextField txtValorAbrirOrdemServico;
    // End of variables declaration//GEN-END:variables
}
