/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author andri
 */
public class BaixaEstoqueGUI extends javax.swing.JFrame {

    /**
     * Creates new form BaixaEstoqueGUI
     */
    public BaixaEstoqueGUI() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelCodigoPecaBaixaEstoque = new javax.swing.JLabel();
        jLabelQuantidadeRemovidaBaixaEstoque = new javax.swing.JLabel();
        txtCodigoPecaBaixaEstoque = new javax.swing.JTextField();
        txtQuantidadeRemoverBaixaEstoque = new javax.swing.JTextField();
        jButtonBaixarEstoque = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Baixa de Estoque");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(509, 367));
        setResizable(false);

        jLabelCodigoPecaBaixaEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCodigoPecaBaixaEstoque.setText("Código da peça");

        jLabelQuantidadeRemovidaBaixaEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelQuantidadeRemovidaBaixaEstoque.setText("Quantidade a ser removida");

        txtCodigoPecaBaixaEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigoPecaBaixaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoPecaBaixaEstoqueActionPerformed(evt);
            }
        });

        txtQuantidadeRemoverBaixaEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtQuantidadeRemoverBaixaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeRemoverBaixaEstoqueActionPerformed(evt);
            }
        });

        jButtonBaixarEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBaixarEstoque.setText("Baixar no Estoque");
        jButtonBaixarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaixarEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelQuantidadeRemovidaBaixaEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCodigoPecaBaixaEstoque)
                    .addComponent(txtCodigoPecaBaixaEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidadeRemoverBaixaEstoque))
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBaixarEstoque)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabelCodigoPecaBaixaEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoPecaBaixaEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabelQuantidadeRemovidaBaixaEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtQuantidadeRemoverBaixaEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonBaixarEstoque)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoPecaBaixaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoPecaBaixaEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPecaBaixaEstoqueActionPerformed

    private void txtQuantidadeRemoverBaixaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeRemoverBaixaEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeRemoverBaixaEstoqueActionPerformed

    private void jButtonBaixarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaixarEstoqueActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Baixa Realizada com sucesso!", "Baixa Estoque", JOptionPane.INFORMATION_MESSAGE);  
    }//GEN-LAST:event_jButtonBaixarEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaixaEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaixaEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaixaEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaixaEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaixaEstoqueGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBaixarEstoque;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCodigoPecaBaixaEstoque;
    private javax.swing.JLabel jLabelQuantidadeRemovidaBaixaEstoque;
    private javax.swing.JTextField txtCodigoPecaBaixaEstoque;
    private javax.swing.JTextField txtQuantidadeRemoverBaixaEstoque;
    // End of variables declaration//GEN-END:variables
}
