/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author andri
 */
public class CadastrarClienteGUI extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarClienteGUI
     */
    public CadastrarClienteGUI() {
        initComponents();
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeCadastrarCliente = new javax.swing.JLabel();
        jLabelIDCadastrarCliente = new javax.swing.JLabel();
        jLabelEnderecoCadastrarCliente = new javax.swing.JLabel();
        jLabelCepCadastrarCliente = new javax.swing.JLabel();
        jLabelCidadeCadastrarCliente = new javax.swing.JLabel();
        jLabelContatoCadastrarCliente = new javax.swing.JLabel();
        jLabelEmailCadastrarCliente = new javax.swing.JLabel();
        txtNomeCadastrarCliente = new javax.swing.JTextField();
        txtIDCadastrarCliente = new javax.swing.JTextField();
        txtEnderecoCadastrarCliente = new javax.swing.JTextField();
        txtCepCadastrarCliente = new javax.swing.JTextField();
        txtCidadeCadastrarCliente = new javax.swing.JTextField();
        txtContatoCadastrarCliente = new javax.swing.JTextField();
        txtEmailCadastrarCliente = new javax.swing.JTextField();
        jButtonCadastrarCliente = new javax.swing.JButton();
        jLabelNumeroCadastrarCliente = new javax.swing.JLabel();
        txtNumeroEnderecoCadastrarCliente = new javax.swing.JTextField();
        jLabelEstadoCadastrarCliente = new javax.swing.JLabel();
        txtEstadoCadastrarCliente = new javax.swing.JTextField();
        jLabelCabecalhoCadastrarCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Cliente");
        setMinimumSize(new java.awt.Dimension(509, 367));
        setResizable(false);

        jLabelNomeCadastrarCliente.setText("Nome do Cliente");

        jLabelIDCadastrarCliente.setText("ID ");

        jLabelEnderecoCadastrarCliente.setText("Endereço");

        jLabelCepCadastrarCliente.setText("CEP");

        jLabelCidadeCadastrarCliente.setText("Cidade");

        jLabelContatoCadastrarCliente.setText("Contato");

        jLabelEmailCadastrarCliente.setText("Email");

        txtNomeCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCadastrarClienteActionPerformed(evt);
            }
        });

        txtIDCadastrarCliente.setEditable(false);

        txtEnderecoCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoCadastrarClienteActionPerformed(evt);
            }
        });

        txtCepCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepCadastrarClienteActionPerformed(evt);
            }
        });

        txtCidadeCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeCadastrarClienteActionPerformed(evt);
            }
        });

        txtContatoCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContatoCadastrarClienteActionPerformed(evt);
            }
        });

        txtEmailCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailCadastrarClienteActionPerformed(evt);
            }
        });

        jButtonCadastrarCliente.setText("Cadastrar");
        jButtonCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarClienteActionPerformed(evt);
            }
        });

        jLabelNumeroCadastrarCliente.setText("Número");

        txtNumeroEnderecoCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroEnderecoCadastrarClienteActionPerformed(evt);
            }
        });

        jLabelEstadoCadastrarCliente.setText("Estado");

        txtEstadoCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoCadastrarClienteActionPerformed(evt);
            }
        });

        jLabelCabecalhoCadastrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCabecalhoCadastrarCliente.setText("CADASTRO DE CLIENTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCadastrarCliente)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelNomeCadastrarCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNomeCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelEnderecoCadastrarCliente)
                                                .addComponent(jLabelCepCadastrarCliente)
                                                .addComponent(jLabelCidadeCadastrarCliente))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtEnderecoCadastrarCliente)
                                                .addComponent(txtCepCadastrarCliente)
                                                .addComponent(txtCidadeCadastrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabelContatoCadastrarCliente)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabelEmailCadastrarCliente)
                                                    .addGap(27, 27, 27)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtContatoCadastrarCliente)
                                                .addComponent(txtEmailCadastrarCliente)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabelIDCadastrarCliente)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtIDCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelNumeroCadastrarCliente)
                                        .addComponent(txtNumeroEnderecoCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelEstadoCadastrarCliente)
                                        .addComponent(txtEstadoCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabelCabecalhoCadastrarCliente)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelCabecalhoCadastrarCliente)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNomeCadastrarCliente)
                    .addComponent(txtNomeCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDCadastrarCliente)
                    .addComponent(txtIDCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnderecoCadastrarCliente)
                    .addComponent(txtEnderecoCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumeroCadastrarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCepCadastrarCliente)
                    .addComponent(txtCepCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroEnderecoCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCidadeCadastrarCliente)
                    .addComponent(txtCidadeCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabelEstadoCadastrarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelContatoCadastrarCliente)
                        .addComponent(txtContatoCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEstadoCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmailCadastrarCliente)
                    .addComponent(txtEmailCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButtonCadastrarCliente)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCadastrarClienteActionPerformed

    private void txtEnderecoCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoCadastrarClienteActionPerformed

    private void txtCepCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepCadastrarClienteActionPerformed

    private void txtCidadeCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeCadastrarClienteActionPerformed

    private void txtContatoCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContatoCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContatoCadastrarClienteActionPerformed

    private void txtEmailCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailCadastrarClienteActionPerformed

    private void txtNumeroEnderecoCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroEnderecoCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroEnderecoCadastrarClienteActionPerformed

    private void txtEstadoCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoCadastrarClienteActionPerformed

    private void jButtonCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarClienteActionPerformed
JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso!", "Cadastro de cliente", JOptionPane.INFORMATION_MESSAGE);  
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarClienteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarCliente;
    private javax.swing.JLabel jLabelCabecalhoCadastrarCliente;
    private javax.swing.JLabel jLabelCepCadastrarCliente;
    private javax.swing.JLabel jLabelCidadeCadastrarCliente;
    private javax.swing.JLabel jLabelContatoCadastrarCliente;
    private javax.swing.JLabel jLabelEmailCadastrarCliente;
    private javax.swing.JLabel jLabelEnderecoCadastrarCliente;
    private javax.swing.JLabel jLabelEstadoCadastrarCliente;
    private javax.swing.JLabel jLabelIDCadastrarCliente;
    private javax.swing.JLabel jLabelNomeCadastrarCliente;
    private javax.swing.JLabel jLabelNumeroCadastrarCliente;
    private javax.swing.JTextField txtCepCadastrarCliente;
    private javax.swing.JTextField txtCidadeCadastrarCliente;
    private javax.swing.JTextField txtContatoCadastrarCliente;
    private javax.swing.JTextField txtEmailCadastrarCliente;
    private javax.swing.JTextField txtEnderecoCadastrarCliente;
    private javax.swing.JTextField txtEstadoCadastrarCliente;
    private javax.swing.JTextField txtIDCadastrarCliente;
    private javax.swing.JTextField txtNomeCadastrarCliente;
    private javax.swing.JTextField txtNumeroEnderecoCadastrarCliente;
    // End of variables declaration//GEN-END:variables
}
